Rails/BlackBelt/config/routes.rb
Rails.application.routes.draw do
  get 'members/create'

  get 'members/update'

  get 'members/index'

  get 'user/new'

  resources :groups
  
  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

Rails/BlackBelt/app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  serialize :users
  has_many :members
  validates :name, :description, :user_id, presence: true
  validates_length_of :name, minimum: 5
  validates_length_of :description, minimum: 10
end

Rails/BlackBelt/app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    has_many :groups
end

Rails/BlackBelt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected
    config.to_prepare do
        Devise::SessionsController.layout "Sign_In"
        Devise::RegistrationsController.layout "Sign_In"
        Devise::ConfirmationsController.layout "Sign_In"
        Devise::UnlocksController.layout "Sign_In"
        Devise::PasswordsController.layout "Sign_In"
    end
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
    end
end

Rails/BlackBelt/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end
  def show
    @members = User.where(id: @group.users); 
    respond_with(@group)
  end

  def create
    @group = Group.new(group_params)
    @group.users = [current_user.id];
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { redirect_to "/groups", alert: "There are errors with your group name or description... Try again" }
      end
    end
  end

  def update
    if group_params[:join] == "join"
      users = @group.users;
	unless users.include?(current_user.id)
      	users.push(current_user.id);
	end
      @group.update(:users => users)
    else
      users = @group.users;
      users.delete(current_user.id);
      @group.update(:users => users);
    end
    redirect_to :back
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description, :user_id, :leave, :join)
    end
end

Rails/BlackBelt/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/BlackBelt/app/helpers/groups_helper.rb
module GroupsHelper
end

Rails/BlackBelt/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/BlackBelt/app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

Rails/BlackBelt/app/views/groups/index.html.erb
<h1>Hi <%=current_user.first_name + " " + current_user.last_name%></h1>
<div class="col-lg-8">
  <h4>Here are all the organizations you may join:</h4>
  <% @groups.each do |group| %>
    <div class="container">
      <h3><%= link_to group.name, group %></h3>
      <p>Members: <%= group.users.length %></p>
      <p><%= group.description %></p>
      <% if current_user.id == group.user.id %>
        <p><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
    </div>
  <% end %>
</div>
<div class="col-lg-4" style="margin-top: 100px; border: solid thick black">
  <h1>New Group</h1>
  <form accept-charset="UTF-8" action="/groups" class="new_group" id="new_group" method="post">
    <div style="display:none">
      <input name="utf8" type="hidden" value="✓">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    </div>
    <div class="field">
      <label for="group_name">Name</label><br>
      <input id="group_name" name="group[name]" type="text">
    </div>
    <div class="field">
      <label for="group_description">Description</label><br>
      <input id="group_description" name="group[description]" type="text">
    </div>
    <input id="group_user_id" name="group[user_id]" value="<%=current_user.id%>" type="hidden">
    <div class="actions">
      <input name="commit" type="submit" value="Create Group">
    </div>
  </form>
</div>
<br>

Rails/BlackBelt/app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

Rails/BlackBelt/app/views/groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Created By:</strong>
  <%= @group.user.first_name + " " +  @group.user.last_name %>
</p>

<p>
  <strong>Members:</strong>
  <ul>
    <% @members.each do |member| %>
    <li><%= member.first_name  + " " + member.last_name %></li>
  <% end %>
  </ul>
</p>
<% if @group.users.include?(current_user.id) %>
<form accept-charset="UTF-8" action="/groups/<%= @group.id %>" class="edit_group" id="edit_group_1" method="post">
  <div style="display:none">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="group[leave]" value="leave">
    <input name="_method" type="hidden" value="patch">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  </div>
  <div class="actions">
    <input name="commit" type="submit" value="Leave Group">
  </div>
</form>
<% else %>
<form accept-charset="UTF-8" action="/groups/<%= @group.id %>" class="edit_group" id="edit_group_1" method="post">
  <div style="display:none">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="group[join]" value="join">
    <input name="_method" type="hidden" value="patch">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  </div>
  <div class="actions">
    <input name="commit" type="submit" value="Join Group">
  </div>
</form>
<% end %>
<%= link_to 'Back', groups_path %>

Rails/BlackBelt/app/views/layouts/Sign_In.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlackBelt" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BlackBelt</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Login", "/users/sign_in"  %></li>
            <li><%= link_to "Sign Up", "/users/sign_up"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

Rails/BlackBelt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlackBelt" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BlackBelt</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Groups", "/groups"  %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>